#!/bin/bash

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
eth="enp0s8"
eth_ip="192.168.100.1"
eth_prefix="24"
eth_mac="08:00:27:FF:9b:78"

# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged together
tap="tap0"