#!/bin/bash

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
eth="enp0s10"
eth_ip="192.168.102.1"
eth_prefix="24"
eth_mac="08:00:27:DF:9b:78"

# Define Bridge Interface
br="br0"

# Define list of TAP interfaces to be bridged together
#tap="tap0"